### ISSUE TITLE
Only Single post shown 

### ISSUE THREAD

**Issue by R0N1n-dev** [nuxt/content#1241]
### Environment

Operating System: Linux
Node Version: v16.13.2
Nuxt Version: 3.0.0-rc.3
Package Manager: npm@8.5.5
Builder: vite
User Config: head, css, plugins, components, buildModules, modules, content, build
Runtime Modules: @nuxt/content@2.0.1
Build Modules: -

### Reproduction

<div class="container">
      <ul>
        <li v-for="{ _path: slug, title } in posts" :key="slug">
          <NuxtLink :to="slug">
            {{ title }}
          </NuxtLink>
        </li>
      </ul>
    </div>
  </template>
  
  <script>
  export default {
    data: () => ({
      posts: null
    }),
    async mounted() {
      const data = await queryContent("/posts")
        .sort({ date: -1 })
        .where({ _partial: false })
        .find();
        this.posts = data;
    },
  };
  </script>```

### Describe the bug

Only one post being shown no matter how many posts are in content/blog folder

**Comment by farnabaz** [comment]
You want to load contents under `content/blog` directory you should write this `queryContent('/blog')`.
If the issue proceeds please consider providing a simple reproduction using https://stackblitz.com/fork/github/nuxt/starter/tree/content

**Comment by R0N1n-dev** [comment]
repo here

https://github.com/R0N1n-dev/nuxt3blog

**Comment by farnabaz** [comment]
I see this is related to a router issue which was fixed in https://github.com/nuxt/framework/pull/4983.
Since it is not released yet, you can use the edge version of nuxt. Change your `package.json` and use `nuxt3` package. 

```diff
- "nuxt": "3.0.0-rc.3"
+ "nuxt": "npm:nuxt3@latest"
```

This resolves your issue.

**Comment by R0N1n-dev** [comment]
Installing nuxt 3 latest didn't solve anything. Problem persists

**Comment by R0N1n-dev** [comment]
Successfully failed.

**Comment by R0N1n-dev** [comment]
Successfully Failed.
No reply.
Headless CMS, here I come
