### ISSUE TITLE
not work with nuxt 3.7 (`Could not resolve import "micromark/lib/postprocess.js"`)

### ISSUE THREAD

**Issue by Jannchie** [nuxt/content#2254]
### Environment

Operating System: Windows_NT
Node Version: v16.20.0
Nuxt Version: 3.7.0
CLI Version: 3.7.0
Nitro Version: 2.6.1
Package Manager: pnpm@8.6.12
Builder: -
User Config: modules
Runtime Modules: @nuxt/content@2.7.2
Build Modules: -

### Reproduction

```bash
npx nuxi@latest init content-app -t content
```

### Describe the bug

It seems that content is currently completely incompatible with nuxt 3.7.

### Logs

```Shell
#  % Jannchie @ JANNCHIE-DESKTOP in D:\code [21:40:31]
$ npx nuxi@latest init content-app -t content
Need to install the following packages:
  nuxi@3.7.0
Ok to proceed? (y) y

✔ Which package manager would you like to use?
pnpm
◐ Installing dependencies...                                                                                  21:40:40
Packages: +721
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: D:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 775, reused 721, downloaded 0, added 721, done

devDependencies:
+ @nuxt/content 2.7.2
+ nuxt 3.7.0

Done in 15.9s
✔ Installation completed.                                                                                    21:40:56
                                                                                                              21:40:56
✨ Nuxt project has been created with the content template. Next steps:
 › cd content-app                                                                                             21:40:56
 › Start development server with pnpm run dev                                                                 21:40:56
(base)
#  % Jannchie @ JANNCHIE-DESKTOP in D:\code [21:40:56]
$ cd .\content-app\
(base)
#  % Jannchie @ JANNCHIE-DESKTOP in D:\code\content-app [21:41:01]
$ pnpm run dev

> @ dev D:\code\content-app
> nuxt dev

Nuxt 3.7.0 with Nitro 2.6.1                                                                                   21:41:04
                                                                                                              21:41:05
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Vite client warmed up in 972ms                                                                             21:41:08

[21:41:09]  WARN  (node-resolve plugin) Could not resolve import "micromark/lib/postprocess.js" in D:\Code\content-app\node_modules\.pnpm\@nuxt+content@2.7.2\node_modules\@nuxt\content\dist\runtime\transformers\csv\from-csv.mjs using exports defined in D:\Code\content-app\node_modules\.pnpm\micromark@4.0.0\node_modules\micromark\package.json.


[21:41:09]  WARN  (node-resolve plugin) Could not resolve import "micromark/lib/preprocess.js" in D:\Code\content-app\node_modules\.pnpm\@nuxt+content@2.7.2\node_modules\@nuxt\content\dist\runtime\transformers\csv\from-csv.mjs using exports defined in D:\Code\content-app\node_modules\.pnpm\micromark@4.0.0\node_modules\micromark\package.json.


[21:41:09]  WARN  (node-resolve plugin) Could not resolve import "micromark/lib/postprocess.js" in D:\Code\content-app\node_modules\.pnpm\@nuxt+content@2.7.2\node_modules\@nuxt\content\dist\runtime\transformers\csv\from-csv.mjs using exports defined in D:\Code\content-app\node_modules\.pnpm\micromark@4.0.0\node_modules\micromark\package.json.


[21:41:09]  WARN  (node-resolve plugin) Could not resolve import "micromark/lib/preprocess.js" in D:\Code\content-app\node_modules\.pnpm\@nuxt+content@2.7.2\node_modules\@nuxt\content\dist\runtime\transformers\csv\from-csv.mjs using exports defined in D:\Code\content-app\node_modules\.pnpm\micromark@4.0.0\node_modules\micromark\package.json.


[21:41:09]  WARN  (node-resolve plugin) Could not resolve import "micromark/lib/postprocess.js" in D:\Code\content-app\node_modules\.pnpm\@nuxt+content@2.7.2\node_modules\@nuxt\content\dist\runtime\transformers\csv\from-csv.mjs using exports defined in D:\Code\content-app\node_modules\.pnpm\micromark@4.0.0\node_modules\micromark\package.json.


[21:41:09]  WARN  (node-resolve plugin) Could not resolve import "micromark/lib/preprocess.js" in D:\Code\content-app\node_modules\.pnpm\@nuxt+content@2.7.2\node_modules\@nuxt\content\dist\runtime\transformers\csv\from-csv.mjs using exports defined in D:\Code\content-app\node_modules\.pnpm\micromark@4.0.0\node_modules\micromark\package.json.


[21:41:09]  WARN  (node-resolve plugin) Could not resolve import "micromark/lib/preprocess.js" in D:\Code\content-app\node_modules\.pnpm\@nuxt+content@2.7.2\node_modules\@nuxt\content\dist\runtime\transformers\csv\from-csv.mjs using exports defined in D:\Code\content-app\node_modules\.pnpm\micromark@4.0.0\node_modules\micromark\package.json.


[21:41:09]  WARN  (node-resolve plugin) Could not resolve import "micromark/lib/postprocess.js" in D:\Code\content-app\node_modules\.pnpm\@nuxt+content@2.7.2\node_modules\@nuxt\content\dist\runtime\transformers\csv\from-csv.mjs using exports defined in D:\Code\content-app\node_modules\.pnpm\micromark@4.0.0\node_modules\micromark\package.json.


[21:41:09]  WARN  (node-resolve plugin) Could not resolve import "micromark/lib/preprocess.js" in D:\Code\content-app\node_modules\.pnpm\@nuxt+content@2.7.2\node_modules\@nuxt\content\dist\runtime\transformers\csv\from-csv.mjs using exports defined in D:\Code\content-app\node_modules\.pnpm\micromark@4.0.0\node_modules\micromark\package.json.


[21:41:09]  WARN  "micromark/lib/preprocess.js" is imported by "node_modules/.pnpm/@nuxt+content@2.7.2/node_modules/@nuxt/content/dist/runtime/transformers/csv/from-csv.mjs", but could not be resolved – treating it as an external dependency.


[21:41:09]  WARN  (node-resolve plugin) Could not resolve import "micromark/lib/postprocess.js" in D:\Code\content-app\node_modules\.pnpm\@nuxt+content@2.7.2\node_modules\@nuxt\content\dist\runtime\transformers\csv\from-csv.mjs using exports defined in D:\Code\content-app\node_modules\.pnpm\micromark@4.0.0\node_modules\micromark\package.json.


[21:41:09]  WARN  "micromark/lib/postprocess.js" is imported by "node_modules/.pnpm/@nuxt+content@2.7.2/node_modules/@nuxt/content/dist/runtime/transformers/csv/from-csv.mjs", but could not be resolved – treating it as an external dependency.

✔ Nitro built in 1460 ms                                                                               nitro 21:41:10

[21:41:10]  ERROR  [worker reload] [worker init] Package subpath './lib/preprocess.js' is not defined by "exports" in D:\Code\content-app\node_modules\micromark\package.json imported from D:\Code\content-app\.nuxt\dev\index.mjs

  at __node_internal_captureLargerStackTrace (node:internal/errors:478:5)
  at new NodeError (node:internal/errors:387:5)
  at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
  at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
  at packageResolve (node:internal/modules/esm/resolve:833:14)
  at moduleResolve (node:internal/modules/esm/resolve:901:20)
  at defaultResolve (node:internal/modules/esm/resolve:1115:11)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
```
```

**Comment by nobkd** [comment]
#2235 might fix that... Not sure though.

**Comment by zhang771** [comment]
Me too. 😊😊😊, Wait or back to 3.6.5😂😂😂

**Comment by xarthurx** [comment]
I can confirm this issue.

**Comment by renewii** [comment]
I can confirm this issue.

**Comment by pi0** [comment]
As a temporary workaround, you can add this to your `nuxt.config` file:

```ts
export default defineNuxtConfig({
  alias: {
    "micromark/lib/preprocess.js": "micromark",
    "micromark/lib/postprocess.js": "micromark",
  },
});
```

**Comment by farnabaz** [comment]
The fix is released on [edge channel](content.nuxtjs.org/guide/migration/edge-channel).
Do you confirm it is fixed on edge channel?

**Comment by Benbinbin** [comment]
> The fix is released on the [edge channel](content.nuxtjs.org/guide/migration/edge-channel). Do you mind trying the edge channel to confirm the fix?

the edge channel link is broken, try this link https://content.nuxtjs.org/guide/migration/edge-channel

**Comment by zhang771** [comment]
Thanks for your job. Now I use edge channel. It's normal🫡🫡🫡

**Comment by veritymedia** [comment]
I had the same issue. Using the edge channel fixed it. However, a new (similar) issue popped up. Cannot find module '[path]/.nuxt/dev/highlighter.mjs' imported from [path]/.nuxt/dev/index.mjs 

:(

**Comment by farnabaz** [comment]
@veritymedia did you try to remove lock file and re-install deps?

**Comment by veritymedia** [comment]
@farnabaz Yes, I did. But I have a feeling that the issue may be somehow tied to the fact that I'm using pnpm with workspaces. I've bashed my head on that particular wall too many times before.

**Comment by jordan-pieces** [comment]
@farnabaz @veritymedia also have deleted and reinstalled deps - but not able to run `dev` environment to get anything to build locally. Using pnpm as well so curious to see what other information either of you have around this - if any updates

**Comment by veritymedia** [comment]
@jordan-pieces I noticed that my nuxt version was 3.0.0 so upgraded manually to 3.7.0. Deleted package-lock for good measure, and now the error is gone. Including nuxt/content in nuxt modules no longer crashes the app

**Comment by xarthurx** [comment]
Is it that before v2.7.3 is released, the fix only exists on the Edge channel?

**Comment by AdiRishi** [comment]
Hey all, just wanted to add some new details here.

> alias: {
>   "micromark/lib/preprocess.js": "micromark",
>   "micromark/lib/postprocess.js": "micromark",
> }

I used the above workaround provided in this thread and it works for the regular node build preset. However, when you run the nuxt build with a different preset, e.g cloudflare-pages there is another error.

Build command - `NITRO_PRESET=cloudflare_pages yarn build`
```
✔ Server built in 1853ms                                                                                                                                                  8:39:23 pm
✔ Generated public dist                                                                                                                                             nitro 8:39:24 pm
ℹ Initializing prerenderer                                                                                                                                          nitro 8:39:24 pm
ℹ Prerendering 1 routes                                                                                                                                             nitro 8:39:25 pm
  ├─ /api/_content/cache.1693305557145.json (310ms)                                                                                                                  nitro 8:39:26 pm
ℹ Building Nitro Server (preset: cloudflare_pages)                                                                                                                  nitro 8:39:26 pm

[nitro 8:39:32 pm]  ERROR  RollupError: "postprocess" is not exported by "../../node_modules/mdast-util-from-markdown/node_modules/micromark/index.js", imported by "../../node_modules/mdast-util-from-markdown/lib/index.js".


148: import {parse} from 'micromark/lib/parse.js'
149: import {preprocess} from 'micromark/lib/preprocess.js'
150: import {postprocess} from 'micromark/lib/postprocess.js'
             ^
151: import {decodeNumericCharacterReference} from 'micromark-util-decode-numeric-character-reference'
152: import {decodeString} from 'micromark-util-decode-string'


[8:39:32 pm]  ERROR  "postprocess" is not exported by "../../node_modules/mdast-util-from-markdown/node_modules/micromark/index.js", imported by "../../node_modules/mdast-util-from-markdown/lib/index.js".

  at error (/PATH_TO_REPO/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Module.error (/PATH_TO_REPO/node_modules/rollup/dist/es/shared/node-entry.js:13716:16)
  at Module.traceVariable (/PATH_TO_REPO/node_modules/rollup/dist/es/shared/node-entry.js:14146:29)
  at ModuleScope.findVariable (/PATH_TO_REPO/node_modules/rollup/dist/es/shared/node-entry.js:12589:39)
  at FunctionScope.findVariable (/PATH_TO_REPO/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
  at ChildScope.findVariable (/PATH_TO_REPO/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
  at Identifier.bind (/PATH_TO_REPO/node_modules/rollup/dist/es/shared/node-entry.js:8309:40)
  at CallExpression.bind (/PATH_TO_REPO/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
  at CallExpression.bind (/PATH_TO_REPO/node_modules/rollup/dist/es/shared/node-entry.js:9875:15)
  at CallExpression.bind (/PATH_TO_REPO/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)



[8:39:32 pm]  ERROR  "postprocess" is not exported by "../../node_modules/mdast-util-from-markdown/node_modules/micromark/index.js", imported by "../../node_modules/mdast-util-from-markdown/lib/index.js".
```

Wanted to add this in case it wasn't considered in the upcoming fix. Hope this helps 😄

**Comment by farnabaz** [comment]
The fix is released in v2.8.0.

**Comment by productdevbook** [comment]
similar problem persists. nuxt 4.0.0-alpha.2

![Image](https://github.com/user-attachments/assets/b0b68603-1384-4d86-a273-05ba71ff910c)
