### ISSUE TITLE
Issues with Nuxt Content V3 and Headers Configuration

### ISSUE THREAD

**Issue by OversensitiveCat** [nuxt/content#3051]
Hi,

I'm encountering issues with Nuxt Content (v3) and the Nuxt Security Module.

Without any specific configuration and without Nuxt Security, navigating between pages causes the application to break with the following error:

> Ignoring inability to install OPFS sqlite3_vfs: Cannot install OPFS: Missing SharedArrayBuffer and/or Atomics. The server must emit the COOP/COEP response headers to enable those. See https://sqlite.org/wasm/doc/trunk/persistence.md#coop-coep

I understand that this issue has already been addressed (#2997).

However, after installing and configuring Nuxt Security (specifically setting crossOriginEmbedderPolicy and crossOriginOpenerPolicy), a new error occurs:

> wasm streaming compile failed: CompileError: WebAssembly.instantiateStreaming(): Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https: 'unsafe-inline' 'strict-dynamic' 'nonce-OaJZEkOdXhQPAsAZeBjfOf0k'"

The solution provided in #2992 suggests adding 'wasm-unsafe-eval' or 'unsafe-eval' to the CSP, which resolves this issue. However, even with this change, I still see the following error in the console when navigating between pages:

> Ignoring inability to install OPFS sqlite3_vfs: The OPFS sqlite3_vfs cannot run in the main thread because it requires Atomics.wait().

Is this error something I should be concerned about? Have I overlooked anything in the documentation?

Thank you for your help!

**Comment by farnabaz** [comment]
You can ignore this warning for now. It will be fixed in the next release.

For your information, as the warning says, OPFS cannot be installed, but it is not an issue for the Content module or the project. OPFS is required when we want to persist the SQL database in localStorage/sessionStorage, which is not the case with Nuxt Content. Nuxt Content create in-memory database and does not persists it in browser storages.

**Comment by OversensitiveCat** [comment]
Ok, thank you :)

**Comment by farnabaz** [comment]
Closing the issue.
Feel free to comment, reopen, or create a new issue if you have further questions.

**Comment by jlemonz** [comment]
> You can ignore this warning for now. It will be fixed in the next release.
> 
> For your information, as the warning says, OPFS cannot be installed, but it is not an issue for the Content module or the project. OPFS is required when we want to persist the SQL database in localStorage/sessionStorage, which is not the case with Nuxt Content. Nuxt Content create in-memory database and does not persists it in browser storages.

Was this fixed in 3.10 ?

**Comment by farnabaz** [comment]
@jlemonz  Are you facing this issue in v3.1.0? The warning should be gone in 3.1.0.

**Comment by jlemonz** [comment]
> [@jlemonz](https://github.com/jlemonz) Are you facing this issue in v3.1.0? The warning should be gone in 3.1.0.

i still got the wasm streaming compile failed: CompileError: WebAssembly.instantiateStreaming(): Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https: 'unsafe-inline' 'strict-dynamic' 'nonce-fcZD6/lOx0yezXT0QzN4uk16'"   -- i thought this was fixed now?

**Comment by jlemonz** [comment]
Ohh wait I think it is fixed. I forgot to set the .path correct in queryCollection. Not sure why i got the message if that is wrong.

**Comment by OversensitiveCat** [comment]
Hello again,

I'm testing it right now, and the warning (Ignoring inability to install OPFS sqlite3_vfs…) is still present in v3.1.0. As before, it only appears in development and does not cause any issues in production.

**Comment by jlemonz** [comment]
> [@jlemonz](https://github.com/jlemonz) Are you facing this issue in v3.1.0? The warning should be gone in 3.1.0.

I cheered to quick. Local everything works besides the example component. But when i push my project to nuxt i get Feb 6, 08:44:54 PM: b6cc0031 ERROR  [nuxt] [request error] [unhandled] [500] unable to open database fileFeb 6, 08:44:54 PM: b6cc0031 INFO   RefImpl {
  dep: Dep {
    computed: undefined,
    version: 0,
    activeLink: undefined,
    subs: undefined,
    map: undefined,
    key: undefined,
    sc: 0
  },
  __v_isRef: true,
  __v_isShallow: false,
  _rawValue: null,
  _value: null
}


So no content is shown. but this is everything i have. Not sure if it related to the error

**Comment by jlemonz** [comment]
![Image](https://github.com/user-attachments/assets/23f76c93-0bf1-4a38-aba9-5b43a38eedb4)  more info

**Comment by jlemonz** [comment]
I did more testing. Only when i disable nuxt security and add  

database: {
      type: "sqlite",
      filename: "/tmp/content.sqlite",
    },-- I use netlify..    

When i enable nuxt security i get these errors. 

![Image](https://github.com/user-attachments/assets/e381f6d8-ba0f-432a-a30e-185f482f5017)

Everything does work local but not in production.

**Comment by OversensitiveCat** [comment]
@jlemonz 

I'm using Netlify and Nuxt Security, and everything works fine (except for the harmless warning in development).

Look at issues #2997 and #2992.

Your nuxt.config.ts should look like this: 

```
export default defineNuxtConfig({
  security: {
    headers: {
      contentSecurityPolicy: {
        'script-src': ["'self'", 'https:', "'strict-dynamic'", "'nonce-{{nonce}}'", "'wasm-unsafe-eval'"],
      },
      crossOriginEmbedderPolicy: 'require-corp',
      crossOriginOpenerPolicy: 'same-origin',
    },
  },
})
```

**Comment by jlemonz** [comment]
> [@jlemonz](https://github.com/jlemonz)
> 
> I'm using Netlify and Nuxt Security, and everything works fine (except for the harmless warning in development).
> 
> Look at issues [#2997](https://github.com/nuxt/content/issues/2997) and [#2992](https://github.com/nuxt/content/issues/2992).
> 
> Your nuxt.config.ts should look like this:
> 
> ```
> export default defineNuxtConfig({
>   security: {
>     headers: {
>       contentSecurityPolicy: {
>         'script-src': ["'self'", 'https:', "'strict-dynamic'", "'nonce-{{nonce}}'", "'wasm-unsafe-eval'"],
>       },
>       crossOriginEmbedderPolicy: 'require-corp',
>       crossOriginOpenerPolicy: 'same-origin',
>     },
>   },
> })
> ```

Thanks. I will test later today. I hope the docs get updated soon with info about nuxt security etc

**Comment by jlemonz** [comment]
@OversensitiveCat   
 
I just tested it. Doesnt work. without adding
 database: {
type: "sqlite",
filename: "/tmp/content.sqlite",
}
Not sure why. Also images wont load wit img anymore. Not sure why. but Nuxtimg will fix it. I think everything is working now. Not sure if adding that database snippet is a problem.
