### ISSUE TITLE
`bunsqlite` polyfills not being loaded (regression in >=3.1)

### ISSUE THREAD

**Issue by MellKam** [nuxt/content#3118]
### Environment

- Operating System: Linux
- Node Version:     v22.11.0
- Nuxt Version:     3.15.4
- CLI Version:      3.21.1
- Nitro Version:    2.10.4
- Package Manager:  bun@1.2.2
- Builder:          -
- User Config:      modules, compatibilityDate, devtools, nitro
- Runtime Modules:  @nuxt/content@3.1.1
- Build Modules:    -

### Version

v3.1

### Reproduction

https://github.com/MellKam/nuxt-content-bun-bug

### Description

Hi. I have a problem with running nuxt + @nuxt/content with bun. After version 3.1 I get the following error that caused by missing polyfills. You can check out the repository for full reproduction. This problem doesn't happen in development, only in production build.

```bash
Database integrity check failed 4526 | });
4527 | 
4528 | async function decompressSQLDump(base64Str, compressionType = "gzip") {
4529 |   const binaryData = Uint8Array.from(atob(base64Str), (c) => c.charCodeAt(0));
4530 |   const response = new Response(new Blob([binaryData]));
4531 |   const decompressedStream = response.body?.pipeThrough(new DecompressionStream(compressionType));
                                                                   ^
ReferenceError: Can't find variable: DecompressionStream
      at <anonymous> (/home/melkam/nuxt-content-bug/.output/server/index.mjs:4531:61)
      at decompressSQLDump (/home/melkam/nuxt-content-bug/.output/server/index.mjs:4528:34)

[nuxt] [request error] [unhandled] [500] no such table: _content_content
```

**Comment by MellKam** [comment]
I think I got it. The problem is this line in bunsqlite connector in db0 library. 

https://github.com/unjs/db0/blob/11c2bf253084b9abc2184bafdbee71f4f5652927/src/connectors/bun-sqlite.ts#L19

```ts
export default function bunSqliteConnector(opts: ConnectorOptions) {
  let _db: Database;
  const getDB = () => {
    if (_db) {
      return _db;
    }
    // we fall in this condition, because we don't provide name in options
    // we provide only `path` property with full path to the file
    if (!opts.name || opts.name === ":memory:") { 
      _db = new Database(":memory:"); 
    } else {
      const filePath = resolve(
        opts.cwd || ".",
        opts.path || `.data/${opts.name || "db"}.bun.sqlite`,
      );
      mkdirSync(dirname(filePath), { recursive: true });
      _db = new Database(filePath);
    }
    return _db;
  };

  return <Connector<Database>>{
    // ...
  };
}
```

I think this is a bug in db0, because if you look at better-sqlite3 connector, they don't have such condition for opts.name.

**Comment by MellKam** [comment]
My PR with fix was merged 😊

We can wait for db0 release and update this dependency

**Comment by farnabaz** [comment]
@MellKam did it fixed in `db0@0.2.4`? You fix is included in that version

**Comment by MellKam** [comment]
> [@MellKam](https://github.com/MellKam) did it fixed in `db0@0.2.4`? You fix is included in that version

Yes, it is fixed in 0.2.4

**Comment by farnabaz** [comment]
I upgrade `db0` version in module, Thanks for you work 🙏

**Comment by asokawotulo** [comment]
Hi, I tried updating to version 3.2.0 but this issue still persists.

Here's a reproduction based on @MellKam's:
https://github.com/asokawotulo/nuxt-content-bun-bug

**Comment by MellKam** [comment]
@farnabaz Ohh fuck, you are right. This is my mistake, I didin't test it in my project yet. I thought that it was fixed because I cloned this repo and tweaked this line to fix db0 bug and it worked.

https://github.com/nuxt/content/blob/49531dd5600de00c8913602875244921bc9cfe27/src/runtime/internal/connectors/bunsqlite.ts#L43

to 

```ts
import type { ConnectorOptions } from 'db0'
import bunSqliteConnector from 'db0/connectors/bun-sqlite'

export default (opts: ConnectorOptions['bun-sqlite']) => {
  return bunSqliteConnector({
    name: opts.path.split('/').pop()!,
  })
}
```

I guess it worked because bundler, for some reason, stopped ignoring this side-effect condition with polyfills because of my exported function. Which is really strange.. But at least bug in db0 was real 😅 

To fix it we can move the condition from global scope to a function, like this:

```
import * as zlib from 'node:zlib'
import type { ConnectorOptions } from 'db0'
import bunSqliteConnector from 'db0/connectors/bun-sqlite'

export default (opts: ConnectorOptions['bun-sqlite']) => {
  /**
   * CompressionStream and DecompressionStream polyfill for Bun
   */
  if (!globalThis.CompressionStream) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const make = (ctx: unknown, handle: any) =>
      Object.assign(ctx, {
        writable: new WritableStream({
          write: (chunk: ArrayBufferView) => handle.write(chunk),
          close: () => handle.end(),
        }),
        readable: new ReadableStream({
          type: 'bytes',
          start(ctrl) {
            handle.on('data', (chunk: ArrayBufferView) => ctrl.enqueue(chunk))
            handle.once('end', () => ctrl.close())
          },
        }),
      })

    // eslint-disable-next-line @typescript-eslint/no-extraneous-class
    globalThis.CompressionStream = class CompressionStream {
      constructor(format: string) {
        make(
          this,
          format === 'deflate'
            ? zlib.createDeflate()
            : format === 'gzip'
              ? zlib.createGzip()
              : zlib.createDeflateRaw(),
        )
      }
    } as unknown as typeof CompressionStream

    // eslint-disable-next-line @typescript-eslint/no-extraneous-class
    globalThis.DecompressionStream = class DecompressionStream {
      constructor(format: string) {
        make(
          this,
          format === 'deflate'
            ? zlib.createInflate()
            : format === 'gzip'
              ? zlib.createGunzip()
              : zlib.createInflateRaw(),
        )
      }
    } as unknown as typeof DecompressionStream
  }

  return bunSqliteConnector(opts)
}
```

**Comment by abd3lraouf** [comment]
I get this error now 

```
SQLITE_ERROR: sqlite3 result code 1: no such table: _content_index
```

**Comment by MellKam** [comment]
> I get this error now
> 
> ```
> SQLITE_ERROR: sqlite3 result code 1: no such table: _content_index
> ```
> 
> is it somehow related ?

No, I don't think so. However, it might be related to issue https://github.com/nuxt/content/issues/3169 But it is already resolved, so I'm not sure
I would recommend you to make a reproduction and open separate issue
