### ISSUE TITLE
Unable to use 2 different collections on 1 page

### ISSUE THREAD

**Issue by mcrapts** [nuxt/content#3182]
### Environment

```
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.15.4
- CLI Version:      3.22.2
- Nitro Version:    2.10.4
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      modules, devtools, future, compatibilityDate
- Runtime Modules:  @nuxt/content@3.2.1
- Build Modules:    -
```

### Version

v3

### Reproduction

https://stackblitz.com/edit/github-grcixd3y?file=app%2Fcomponents%2FNavBar.vue

### Description

Querying from two different content collections on one page does not work after SSR. On initial page load it works, but querying again client-side does not work properly. The second promise never resolves.

### Logs

```shell-script

```

**Comment by rijkvanzanten** [comment]
I'm running into the same issue. Tried as two `useAsyncData` blocks first:

```ts
const { data: page } = await useAsyncData('/posts', () => {
	return Promise.all([
		queryCollection('pages').path('/posts').first(),
	]);
});

const { data: posts } = await useAsyncData('$posts-list', () => {
	return queryCollection('posts').select('path', 'title', 'date').order('date', 'DESC').all();
});
```

but on navigation only one of the two would work. On reload both datasets show up. 

At first I thought maybe the two separate `useAsyncData` blocks were to blame, but the same error happens when using a single useAsyncData with a `Promise.all`.

The error that's throw in `queryCollection` is 

```
SQLite3Error: SQLITE_ERROR: sqlite3 result code 1: no such table: _content_posts
    at toss3 (sqlite3-bundler-friendly.mjs?v=407609e1:10181:17)
    at checkSqlite3Rc (sqlite3-bundler-friendly.mjs?v=407609e1:10200:13)
    at DB.checkRc (sqlite3-bundler-friendly.mjs?v=407609e1:10520:42)
    at DB.exec (sqlite3-bundler-friendly.mjs?v=407609e1:10654:20)
    at Object.all (database.client.js?v=407609e1:18:17)
```

which looks very similar to https://github.com/nuxt/content/issues/3181

**Comment by hasan-ozbey** [comment]
I am not sure but could this be related with https://github.com/nuxt/content/discussions/3183 ?

**Comment by rijkvanzanten** [comment]
Luckily this doesn't seem to happen in the production build (in my case the static output from `nuxi generate`), which makes it a bit more of a nuisance than a critically severe issue. Your mileage may vary when using SSR though!

**Comment by farnabaz** [comment]
This is fixed in #3188 and will be released today 
Meanwhile you can use pr release to approve the behavior

```
npm i https://pkg.pr.new/@nuxt/content@3188
```

**Comment by hasan-ozbey** [comment]
okay now I am super confused. #3188 did not solve my issue but everything is fine with 3.1.1 on my end, is this an another bug? 

Curious if that works for others too, @rijkvanzanten @endquote

**Comment by farnabaz** [comment]
@hasan-ozbey Could you share small reproduction using `https://pkg.pr.new/@nuxt/content@3188`? I'll be happy to found the cause before today's release

**Comment by endquote** [comment]
The PR build fixed it for me, tried dev/build/preview.

My repro is pretty simple.

```
<script setup lang="ts">
const route = useRoute();
const { data: page } = await useAsyncData(() => queryCollection("content").path(route.path).first());
const { data: projects } = await useAsyncData(() => queryCollection("projects").order("date", "DESC").all());
</script>
```

**Comment by hasan-ozbey** [comment]
ahhh! It was a cache issue, the PR build is also fixed for me. Thank you so much, @farnabaz.

**Comment by rijkvanzanten** [comment]
@farnabaz confirmed on my end as well. Problem resolved when using `https://pkg.pr.new/@nuxt/content@3188` 🙂

**Comment by farnabaz** [comment]
Glad to hear it. I'll release the patch ASAP
