### ISSUE TITLE
Problem deploying on Vercel and better-sqlite3

### ISSUE THREAD

**Issue by ValentinOsvaldo** [nuxt/content#3424]
I'm using `@nuxt/content` version **3.6.0**, and deploying my Nuxt app to **Vercel**.  
I configured the `content.database` to use **PostgreSQL** hosted on **Neon**.

However, during deployment I encounter the following error:

![Image](https://github.com/user-attachments/assets/5b4fce3b-f3d0-4885-a5fe-90791053087c)

Here is my relevant `nuxt.config.ts` snippet:

```ts
export default defineNuxtConfig({
  content: {
    database: {
      type: 'postgres',
      url: process.env.POSTGRES_URL!,
    },
    preview: {
      api: 'https://api.nuxt.studio',
      dev: true,
      gitInfo: {
        name: 'valen.vue',
        owner: 'ValentinOsvaldo',
        url: 'https://github.com/ValentinOsvaldo/valen.vue.git',
      },
    },
    renderer: {
      anchorLinks: false,
    },
  }
})
```

I try to create a new deploy but the error persists

**Comment by edimitchel** [comment]
Hi,

When you install locally, it should ask you this too. Which version of Node do you have ?

**Comment by ValentinOsvaldo** [comment]
> Hi,
> 
> When you install locally, it should ask you this too. Which version of Node do you have ?

I'm currently using Node.js version `v22.14.0` on my local machine, and Vercel runs `22.x`. I'm also using Bun as my package manager, and my Nuxt version is `"nuxt": "^3.17.5"`.

Even when I run the build locally, it still generates the `.data/` folder, and I encounter the same issue when deploying to Netlify.

**Comment by farnabaz** [comment]
Thanks for the report, this should be fixed in #3425 
I appreciate if you check with pr-release and verify the fix

```bash
https://pkg.pr.new/@nuxt/content@3425
```

**Comment by ValentinOsvaldo** [comment]
> Thanks for the report, this should be fixed in [#3425](https://github.com/nuxt/content/pull/3425) I appreciate if you check with pr-release and verify the fix
> 
> https://pkg.pr.new/@nuxt/content@3425

I appreciate your help, but my problem persists.

I can share you my repo  with you
https://github.com/ValentinOsvaldo/valen.vue

**Comment by farnabaz** [comment]
I see, thanks for the repo.
What is your development environment?
Content module requires a SQL connector in order to parse/cache and generate the database dump. Try enabling native sqlite, it will solve your issue in Vercel.

https://content.nuxt.com/docs/getting-started/configuration#experimentalnativesqlite

**Comment by ValentinOsvaldo** [comment]
> I see, thanks for the repo. What is your development environment? Content module requires a SQL connector in order to parse/cache and generate the database dump. Try enabling native sqlite, it will solve your issue in Vercel.
> 
> https://content.nuxt.com/docs/getting-started/configuration#experimentalnativesqlite

Thanks, it works.

I added these lines to `nuxt.config`
```ts
experimental: {
  sqliteConnector: 'native',
},
```

**Comment by farnabaz** [comment]
@ValentinOsvaldo I still wonder, what is your development environment?
Content module should prompt for installing better-sqlite pacakge on development.

**Comment by ValentinOsvaldo** [comment]
> [@ValentinOsvaldo](https://github.com/ValentinOsvaldo) I still wonder, what is your development environment? Content module should prompt for installing better-sqlite pacakge on development.

Hi! I'm using **Windows 11** as my development environment. I initially created the project using:

```bash
bun create nuxt <project-name>
```

Then I installed `@nuxt/content`. However, I later switched from **Bun** to **pnpm** as my package manager.

The project uses Nuxt 3 (`"nuxt": "^3.17.5"`) and `@nuxt/content` (version 3.6.1). I've configured it to use **PostgreSQL** hosted on **Neon**, and I'm explicitly setting the `database` option in my `nuxt.config.ts`:

```ts
export default defineNuxtConfig({
  content: {
    database: {
      type: 'postgres',
      url: process.env.POSTGRES_URL,
    },
    preview: {
      dev: true,
      api: 'https://api.nuxt.studio',
    },
  },
})
```

In development, I was **never prompted to install `better-sqlite3`**, which is fine.  
However, the `.data/content` folder is still being generated after running `pnpm build` (previously `bun run build`), even though I'm not using SQLite at all.

**Comment by farnabaz** [comment]
Thanks for the info

> However, the .data/content folder is still being generated after running pnpm build (previously bun run build), even though I'm not using SQLite at all.

Just to mention, Content module always uses sqlite database in development to cache parsed contents and improve restart performance.
