### ISSUE TITLE
Error: Cannot find module 'detab'

### ISSUE THREAD

**Issue by konstanzzz** [nuxt/content#448]
### Version
@nuxt/content: 1.7.1
nuxt: 2.14.4

### Steps to reproduce
1. Create project with nuxt 2.14.4 and content 1.7.1.
2. Run `yarn nuxt`

### What is Expected?
No error

### What is actually happening?
Getting the following error:
```
Nuxt Fatal Error  
           
Error: Cannot find module 'detab'  
Require stack:  

- /sandbox/node_modules/@nuxt/content/parsers/markdown/handlers/code.js  
- /sandbox/node_modules/@nuxt/content/parsers/markdown/handlers/index.js 
- /sandbox/node_modules/@nuxt/content/parsers/markdown/index.js  
- /sandbox/node_modules/@nuxt/content/parsers/index.js  
- /sandbox/node_modules/@nuxt/content/lib/database.js  
- /sandbox/node_modules/@nuxt/content/lib/index.js  
- /sandbox/node_modules/@nuxt/core/dist/core.js  
- /sandbox/node_modules/@nuxt/cli/dist/cli-index.js  
- /sandbox/node_modules/@nuxt/cli/dist/cli.js  
- /sandbox/node_modules/nuxt/bin/nuxt.js     
```

**Comment by evaleries** [comment]
Simply run ```bash yarn add detab```.
I've tried and it works.

**Comment by konstanzzz** [comment]
Yes, but that would mean if I decided to stop using content I would have to remove detab myself too. It's no big deal really, but I still think this is a bug that should be fixed, because these dependencies shouldn't be managed by the users.

**Comment by clotairedamy** [comment]
Have the same issue with detab. Tried to add Detab via NPM and the issue is still there.

**Comment by ludo237** [comment]
This error popped up right now for me, never had an issue with nuxt content since today

**Comment by mathe42** [comment]
Problem is https://github.com/syntax-tree/mdast-util-to-hast/commit/914a6b77b9d363c588dcc6ef61f96053ec1b3b1e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 I create a PR in a mom
